name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      deploy_target:
        description: "Select deployment target"
        required: true
        type: choice
        options:
          - backend
          - frontend
          - both

jobs:

  backend-deploy:
    if: |
      github.event.inputs.deploy_target == 'backend' ||
      github.event.inputs.deploy_target == 'both'

    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Backend
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'

            cd /home/argus/argus

            git pull origin main

            sudo systemctl restart argus

            sudo systemctl status argus --no-pager

          EOF

  frontend-deploy:
    if: |
      github.event.inputs.deploy_target == 'frontend' ||
      github.event.inputs.deploy_target == 'both'

    name: Deploy Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Create .env
        run: |
          cat <<EOF > .env
          VITE_API_URL=${{ secrets.VITE_API_URL }}
          EOF

      - name: Build Frontend
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Upload To S3
        run: |
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }}/ --delete
